### PR TITLE
ISSUE 36: Switch to non-root account for Docker image

### PR DESCRIPTION
**Pull request by vweckerle**
Example PR for https://github.com/nats-nui/nui/issues/36

### CODE REVIEW

**Review by rud — APPROVED** [review]
Seems reasonable. Does it still work as intended?

**Comment by pricelessrabbit** [comment]
I need to test it with existing containers that have the db created as a root user, and to check if uid 2 is always reasonable in the host users or is better to create a separate nui user to run the container

**Comment by vweckerle** [comment]
I kept the PR simple. But for our internally used containers we indeed also create a dedicated application user and use that one instead of relying on any users which come with the base image. You never know what might change in the passwd file of the base image with newer versions after all.

**Comment by pricelessrabbit** [comment]
i'm closing this one in favor of #43, that is backward compatible with existing version. Let me know if you see some hotspots in that 🐰

**Pull request closed without merging**
